[package]
name = "omarchygram"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
async-channel = "2.5.0"
chrono = "0.4.45"
dirs = "6.0.0"
grammers-client = { version = "0.10.0", features = ["markdown"] }
grammers-session = "0.10.0"
grammers-tl-types = "0.10.0"
gtk4 = { version = "0.11.4", features = ["v4_12"] }
image = "0.25.10"
libsql = { version = "0.9.30", default-features = false, features = ["core"] }
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "json", "multipart"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time", "process", "fs", "io-util"] }
toml = "1.1.4"
